services:
  - type: web
    name: wordle-web
    runtime: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start:prod
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18.20.4
      - key: NODE_OPTIONS
        value: '--max_old_space_size=512'
      - key: PORT
        value: 10000
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
    healthCheckPath: /
